// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCElamR55qyFjfxHY4XQgM0917Iab4jROA',
    appId: '1:558132453158:web:ee719ec149ea49e81a2be7',
    messagingSenderId: '558132453158',
    projectId: 'todo-41e61',
    authDomain: 'todo-41e61.firebaseapp.com',
    storageBucket: 'todo-41e61.appspot.com',
    measurementId: 'G-EZVNFJN2C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxJxn0jbrQHIN7ifAVzJGs_-qbCB5ACMI',
    appId: '1:558132453158:android:c6e810e38c278e471a2be7',
    messagingSenderId: '558132453158',
    projectId: 'todo-41e61',
    storageBucket: 'todo-41e61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZBvuXHeCW6rMXYMRiEDCJDehi95MZh0',
    appId: '1:558132453158:ios:0df402a1f6e589421a2be7',
    messagingSenderId: '558132453158',
    projectId: 'todo-41e61',
    storageBucket: 'todo-41e61.appspot.com',
    iosClientId: '558132453158-36htgintt1m7bph9qosi6rc1q7n70an8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZBvuXHeCW6rMXYMRiEDCJDehi95MZh0',
    appId: '1:558132453158:ios:0df402a1f6e589421a2be7',
    messagingSenderId: '558132453158',
    projectId: 'todo-41e61',
    storageBucket: 'todo-41e61.appspot.com',
    iosClientId: '558132453158-36htgintt1m7bph9qosi6rc1q7n70an8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCElamR55qyFjfxHY4XQgM0917Iab4jROA',
    appId: '1:558132453158:web:5f5533adc825456f1a2be7',
    messagingSenderId: '558132453158',
    projectId: 'todo-41e61',
    authDomain: 'todo-41e61.firebaseapp.com',
    storageBucket: 'todo-41e61.appspot.com',
    measurementId: 'G-P5DF4CPX8T',
  );
}
